name: house_solution
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.1
  firebase_database: ^11.0.1
  shared_preferences: ^2.3.2
  hexcolor: ^2.0.7
  icons_plus: ^4.0.0
  font_awesome_flutter: ^10.1.0
  otp_text_field: ^1.1.1
  image_picker: ^1.1.2
  multi_select_flutter: ^4.0.0
  firebase_storage: ^12.3.3
  http: ^1.2.2
  path_provider: ^2.1.4
  cached_network_image: ^3.3.1
  intl_utils: ^2.8.7
  pdf: ^3.11.1
  printing: ^5.13.3
  flutter_timezone: ^3.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/Screenshot 2024-06-20 225354.png
    - assets/house.png
    - assets/images/

# Configuration for generating app icons
flutter_icons:
  android: true
  ios: true  # Enable this if you want iOS icons as well
  image_path: "assets/house.png"
